// Created: 2026-10-04 by Constructor Tech
// Updated: 2026-10-06 by Constructor Tech
//! Runs the SDK's `CredStorePluginClientV2` conformance suite against the
//! plugin and a real `hashicorp/vault` dev server in Docker: one test per
//! check, each with its own server and a plugin that authenticates with a
//! token holding only the minimal ACL policy of `docs/DESIGN.md`.
//!
//! All tests are `#[ignore]`d (they need Docker and never run in CI):
//!
//! ```text
//! cargo test -p cf-gears-vault-credstore-plugin --test conformance -- --ignored
//! ```
//!
//! The suite is generated by the SDK's public
//! `credstore_sdk::credstore_plugin_conformance!`, whose outer attributes
//! (here `#[ignore = ...]`) are applied to every generated test.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    reason = "integration tests: a setup failure IS the test failure"
)]

mod common;

use async_trait::async_trait;
use common::VaultFixture;
use credstore_sdk::{
    CredStoreError, CredStorePluginClientV2, DestroySelector, SecretValue, StoreKey, ValueVersion,
};
use toolkit_security::SecurityContext;
use vault_credstore_plugin::domain::Service;

/// The plugin under test together with the Vault container it talks to. The
/// suite's factory expression yields a single value, and the container lives
/// exactly as long as the value does.
struct PluginWithServer {
    _server: VaultFixture,
    plugin: Service,
}

impl PluginWithServer {
    fn new(server: VaultFixture) -> Self {
        let plugin = server.plugin();
        Self {
            _server: server,
            plugin,
        }
    }
}

#[async_trait]
impl CredStorePluginClientV2 for PluginWithServer {
    async fn put(
        &self,
        ctx: &SecurityContext,
        key: &StoreKey,
        value: SecretValue,
    ) -> Result<ValueVersion, CredStoreError> {
        self.plugin.put(ctx, key, value).await
    }

    async fn get(
        &self,
        ctx: &SecurityContext,
        key: &StoreKey,
        version: &ValueVersion,
    ) -> Result<Option<SecretValue>, CredStoreError> {
        self.plugin.get(ctx, key, version).await
    }

    async fn delete_key(
        &self,
        ctx: &SecurityContext,
        key: &StoreKey,
    ) -> Result<(), CredStoreError> {
        self.plugin.delete_key(ctx, key).await
    }

    fn supports_destroy(&self) -> bool {
        self.plugin.supports_destroy()
    }

    async fn destroy(
        &self,
        ctx: &SecurityContext,
        key: &StoreKey,
        selector: DestroySelector,
    ) -> Result<(), CredStoreError> {
        self.plugin.destroy(ctx, key, selector).await
    }
}

// The factory is expanded inside each generated test, so `return` ends that
// test early when Docker is not reachable (the fixture prints why; with
// `VAULT_CREDSTORE_REQUIRE_DOCKER=1` it fails instead).
credstore_sdk::credstore_plugin_conformance!(
    #[ignore = "requires Docker (starts a hashicorp/vault container); run manually with `-- --ignored`"]
    {
        let Some(server) = VaultFixture::start().await else {
            return;
        };
        PluginWithServer::new(server)
    }
);
